# Generated by Django 5.0.2 on 2024-03-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_rename_id_livro_emprestimo_livro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='endereço',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='instituicao',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cidade_estado',
            field=models.CharField(default='Cidade/Estado', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome_completo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
