# Generated by Django 5.0.2 on 2024-03-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_remove_livro_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='status',
            new_name='disponivel',
        ),
    ]
