# Generated by Django 5.0.2 on 2024-03-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_rename_status_emprestimo_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='idade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='instituicao',
            field=models.CharField(default='Instituição', max_length=255),
        ),
    ]
